### ISSUE TITLE
unicorn-emulate's bug

### ISSUE THREAD

**Issue by lieanu** [hugsy/gef#19]
```shell
gef> unicorn-emulate -n 3
Python Exception <type 'exceptions.TypeError'> unsupported operand type(s) for -: 'NoneType' and 'long': 
Error occurred in Python command: unsupported operand type(s) for -: 'NoneType' and 'long'
```

Thanks to such an awesome tool! :smile:

**Comment by hugsy** [comment]
Hi,

Thanks for the feedback. I've actually updated `gef` a few hours ago on the `unicorn-emulate` command (see 2052d3931420d10135418808e5a9a07b53df79c4).

Please try again and let me know. If you still have errors, try to add as much detail as you can.

**Comment by lieanu** [comment]
Hey, 

Thanks for your reply. `unicorn-emulate -n xxx` works.
Testcase from 32C3 ctf: [https://github.com/ctfs/write-ups-2015/tree/master/32c3-ctf-2015/pwn/readme-200](https://github.com/ctfs/write-ups-2015/tree/master/32c3-ctf-2015/pwn/readme-200)

unicorn-emulate also will fails on `0x4007fc         mov    QWORD PTR [rsp+0x108],rax` instr.
And a warning `[*] Cannot copy page=0x2aaaaaace000-0x2aaaaaad0000 : Cannot access memory at address 0x2aaaaaace000`


```asm
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------[code:i386:x86-64]--
0x4007e1         mov    esi,0x400934
0x4007e6         mov    edi,0x1
0x4007eb         push   rbx
0x4007ec         sub    rsp,0x118
0x4007f3         mov    rax,QWORD PTR fs 0x28            <- $pc
0x4007fc         mov    QWORD PTR [rsp+0x108],rax
0x400804         xor    eax,eax
0x400806         call   0x4006b0 <__printf_chk@plt>
0x40080b         mov    rdi,rsp
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------[trace]--
#0  0x00000000004007f3 in ?? ()
#1  0x00002aaaaace0028 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00002aaaaaad34c0 in ?? ()
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
0x00000000004007f3 in ?? ()
gef> unicorn-emulate -n 1
[*] Cannot copy page=0x2aaaaaace000-0x2aaaaaad0000 : Cannot access memory at address 0x2aaaaaace000
[+] Starting emulation: 0x4007f3 -> -0x1
[!] An error occured during emulation: Invalid memory read (UC_ERR_READ_UNMAPPED)
gef> unicorn-emulate -n 2
[*] Cannot copy page=0x2aaaaaace000-0x2aaaaaad0000 : Cannot access memory at address 0x2aaaaaace000
[+] Starting emulation: 0x4007f3 -> -0x1
[!] An error occured during emulation: Invalid memory read (UC_ERR_READ_UNMAPPED)
gef> vmmap 
             Start                End             Offset Perm Path
0x0000000000400000 0x0000000000401000 0x0000000000000000 r-x /mnt/hgfs/lieanu/ctf/32c3/pwn/readme/readme.bin
0x0000000000600000 0x0000000000601000 0x0000000000000000 rw- /mnt/hgfs/lieanu/ctf/32c3/pwn/readme/readme.bin
0x00002aaaaaaab000 0x00002aaaaaace000 0x0000000000000000 r-x /lib/x86_64-linux-gnu/ld-2.19.so
0x00002aaaaaace000 0x00002aaaaaad0000 0x0000000000000000 r-- [vvar]
0x00002aaaaaad0000 0x00002aaaaaad2000 0x0000000000000000 r-x [vdso]
0x00002aaaaaad2000 0x00002aaaaaad4000 0x0000000000000000 rw- 
0x00002aaaaaaef000 0x00002aaaaaaf2000 0x0000000000000000 rw- 
0x00002aaaaaccd000 0x00002aaaaacce000 0x0000000000022000 r-- /lib/x86_64-linux-gnu/ld-2.19.so
0x00002aaaaacce000 0x00002aaaaaccf000 0x0000000000023000 rw- /lib/x86_64-linux-gnu/ld-2.19.so
0x00002aaaaaccf000 0x00002aaaaacd0000 0x0000000000000000 rw- 
0x00002aaaaacd0000 0x00002aaaaae8b000 0x0000000000000000 r-x /lib/x86_64-linux-gnu/libc-2.19.so
0x00002aaaaae8b000 0x00002aaaab08a000 0x00000000001bb000 --- /lib/x86_64-linux-gnu/libc-2.19.so
0x00002aaaab08a000 0x00002aaaab08e000 0x00000000001ba000 r-- /lib/x86_64-linux-gnu/libc-2.19.so
0x00002aaaab08e000 0x00002aaaab090000 0x00000000001be000 rw- /lib/x86_64-linux-gnu/libc-2.19.so
0x00002aaaab090000 0x00002aaaab095000 0x0000000000000000 rw- 
0x00007ffffffde000 0x00007ffffffff000 0x0000000000000000 rw- [stack]
0xffffffffff600000 0xffffffffff601000 0x0000000000000000 r-x [vsyscall]

```

**Comment by hugsy** [comment]
Yes, I am aware of the bug with the segmentation register.
I haven't figured out a solution yet... If you have any idea, don't hesitate.

**Comment by lieanu** [comment]
Unicorn cannot handle x86 seg regs? but it seems that unicorn had fixed it.
https://github.com/unicorn-engine/unicorn/pull/422

**Comment by hugsy** [comment]
Can you pull again, make sure that you have commit ae8ed96 and try again?

**Comment by lieanu** [comment]
Awesome!  It works now. :+1: :+1: :+1:

**Comment by lieanu** [comment]
```asm
0x4007f3         mov    rax,QWORD PTR fs 0x28            <- $pc
0x4007fc         mov    QWORD PTR [rsp+0x108],rax
0x400804         xor    eax,eax
0x400806         call   0x4006b0 <__printf_chk@plt>
0x40080b         mov    rdi,rsp
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------[trace]--
#0  0x00000000004007f3 in ?? ()
#1  0x00002aaaaace0028 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00002aaaaaad3578 in ?? ()
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
0x00000000004007f3 in ?? ()
gef> unicorn-emulate -n 1
[*] Cannot copy page=0x2aaaaaace000-0x2aaaaaad0000 : Cannot access memory at address 0x2aaaaaace000
[+] Starting emulation: 0x4007f3 -> -0x1
[+] Stopping emulation on user's demand (max_instructions reached)
[+] Emulation ended, showing tainted registers:
[+] $rax       : old=0x00002aaaab08f400 || new=0x0000000000000000
[+] $rip       : old=0x00000000004007f3 || new=0x00000000004007fc
[+] $gs        : old=0x0000000000000000 || new=0x0000000000001000
```

`[*] Cannot copy page=0x2aaaaaace000-0x2aaaaaad0000 : Cannot access memory at address 0x2aaaaaace000`
How to eliminate this warning?

**Comment by hugsy** [comment]
It is only there for the development phase.
It will be removed soon.

Thanks for testing.
